### ISSUE TITLE
Updates to the protocol info

### ISSUE THREAD

**Issue by berarma** [dhallgb/Seneye-MQTT#2]
Hi there.

I hope you're well.

I've been playing with a Seneye Reef v2.0.16 and have found your protocol info very handy. I've updated it with some info that was lacking or incorrect. See PR #1. Or maybe it's just that the new firmware has changed some things. I don't know.

I've written a library and shell command to control the device that I'd like to share. I've just hit a problem: the device stops responding and gets disconnected when there's (supposedly) a sudden change in lighting or gets out of the water. I can't even get any reading with the device out of the water. I haven't introduced the slide yet. It works well with the SCA.

It doesn't seem to be related to any buffer getting full. It happens even just after uploading all saved data. I have to reconnect the device to get it working again. This makes it unreliable to use in this way.

The device seems to have 2 modes of operation, the one we're using based on HID, and a propietary one. I've noticed that when the HELLOSUD command is issued the alert leds go off until the BYESUD is issued. This doesn't happen with the SCA. I've also used a USB sniffer and the messages are totally different and undecipherable.

I've just written to Seneye support asking nicely to help me write software for their device. Wish me luck.

Are you using yours yet? Do you have some more info to share or want to collaborate?

Regards.

**Comment by dhallgb** [comment]
Thanks for your contribution and the updates to the protocol. I will take a look at the pull request now and welcome any other changes you wanted to make.
Due to the limitations in the SUD protocol based on the code released by Seneye I no longer use it for my device, so are not actively developing the code. However, many people worldwide read my blog at https://doughall.me/2017/07/03/seneyemqttpt3/ and recently Gert Nelen talked in the comments on that article about the improvements he had made to my original code. You may like to connect with Gert if you wish to actively take this forward, as he is looking at this right now.
Seneye themselves have starred my repo, so I know they are aware of my code. I long suspected that there are other flows which, for commercial reasons, they have not exposed and some of these deal with draining down the data collection and other things.

**Comment by berarma** [comment]
Thanks. I had read your blog entry but hadn't read the last comments. I'll try to contact him.

May I ask what device are you currently using for the job if any?

**Comment by dhallgb** [comment]
I converted a LattePanda into an aquarium computer, documented later in my blog - https://doughall.me/2017/08/04/housing-an-aquarium-computer. I also explored a tracking webcam on the side of the aquarium housed in a Raspberry Pi Zero.
